### ISSUE TITLE
File already Exists Copressed GLTF export

### ISSUE THREAD

**Issue by masonrk12121** [KhronosGroup/glTF-Compressor#17]
zip-writer.js:142 Uncaught (in promise) Error: File already exists
    at ZipWriter.add (zip-writer.js:142:11)
    at main.js:758:34
    at Array.map (<anonymous>)
    at SafeSubscriber._next (main.js:756:50)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:192:16)
    at SafeSubscriber.next (Subscriber.js:130:22)
    at Subscriber._next (Subscriber.js:76:26)
    at Subscriber.next (Subscriber.js:53:18)
    at MapSubscriber._next (map.js:41:26)
    at Subscriber.next (Subscriber.js:53:18)

**Comment by masonrk12121** [comment]
This is with an uploaded gltf

**Comment by abasilak** [comment]
Thanks for reporting. Can you include the steps that you followed in order to reproduce it?
